### PR TITLE
Knight

### PR DESCRIPTION
**Pull request by fisiceoir**
The parallelized sum is not correct, since there is still the chance t
    hat the variables local_sum will write to sum at the same time.
 
 The time taken is between 0.5 ms and 5 ms.

### CODE REVIEW

**Comment by fisiceoir** [comment]
Adding the #pragma omp critical part allows for the sum to be correct
    at 0.782577, and the time taken for it to run is about unchanged.

**Comment by fisiceoir** [comment]
Changing #pragma omp critical to atomic gave no significant changes to
     processing time, and still gave the correct answer.

**Comment by fisiceoir** [comment]
Adding the reduction component seems to have dropped the time by about
     half, to about 1-3 ms, and it still gives the correct response.

**Comment by fisiceoir** [comment]
Increasing the number of intervals seems to have no effect until about 100000, and then each factor of 10 increase takes about 2 times longer.

**Comment by germasch** [comment]
So fundamentally, it looks like you've observed the expected behavior, though you never say anything about what you expected.

The timing numbers you give are kinda vague, I suppose because they were varying wildly. So I think you should have done the last part first, ie, increase the number of intervals until you get more stable timing results once the calculation becomes more involved.

I can not believe that increasing the number of intervals by 10x will only slow down the code by 2x, since there's 10x as much work to be done.

Also, I had asked for a scaling study (vary number of threads and measure performance), which I believe is missing?

1/2

**Pull request closed without merging**
